
name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}   
      run: echo "Mohitjoshi@155" |
        docker login -u mohitjoshi155 --password-stdin 
           
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mohitjoshi155/sabnzbd-rclone-autoupload:latest
      
    - name: Docker Push
      run: docker push mohitjoshi155/nzbget-gcloner
